### PR TITLE
feat: import call logs

### PR DESCRIPTION
**Pull request by vbh**

### CODE REVIEW

**Comment by tmo1** [comment]
Hi,

Thanks for this! I recently did a significant refactor of the existing code, for modularity and consistency, which I have not yet pushed to the public repo, so I'll have to examine this PR after I push the refactor.

Thanks again.

**Comment by tmo1** [comment]
I've pushed the reorganized code to the repo. IIRC, the main change is the relocation of the actual import / export code to the new file `ImportExport.kt`, with `MainActivity.kt` now containing mainly the UI code. If you can reorganize your PR code accordingly, I'll review it and merge it if everything looks good.

**Comment by vbh** [comment]
@tmo1 made the requested changes, can you review it?

**Comment by tmo1** [comment]
> @tmo1 made the requested changes, can you review it?

Sorry for not getting back to you earlier - I'll try to get to it in the next day or two, and merge it if everything looks good. Thanks again, and I apologize for the delay.

**Pull request merged**
