### PR TITLE
Fix truncated text in about page in horizontal view

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Here is a screenshot of the about page before this fix. See texts are not shown in top and bottom lines.

image

This is fixed by adding a scroll view.

**Comment by Biswa96** [comment]
p.s. The diff may look bigger but most of it is just for indentation.

**Comment by tmo1** [comment]
Hi,

Thanks for working on this. Can you please try to modify the patch to reduce the size of the diff? It's difficult to review in the current form.

**Comment by Biswa96** [comment]
I have removed the indentation changes in new commit.

**Comment by tmo1** [comment]
Thank you!

**Pull request merged**
