### PR TITLE
new icon!

### PR DESCRIPTION
**Pull request by Donnnno**
Applied it to all the parts

here's a zip with the svg:

[sms-ie.zip](https://github.com/tmo1/sms-ie/files/8353352/sms-ie.zip)

Also some attribution bellow, for  on github or in the app idk.

----

SMS Import / Export icon

Copyright 2022 Onno van den Dungen

Licensed under CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/

### CODE REVIEW

**Review by tmo1 — CHANGES_REQUESTED** [review]
Thank you!

1) Please leave at least some of the copright block in the text (XML) files, with appropriate modifications, e.g.:

```
~  SMS Import / Export: a simple Android app for importing and exporting SMS messages from and to JSON files.
~  This file is part of SMS Import / Export.
~  This file is copyright (c) 2022 <your name>.
```

After that, you can either include the GPL boilerplate that I had, if you're willing to license the text files under the GPL, or replace it with CC boilerplate if you want the text files to be under the CC license.

2) Please ensure that all files end with newlines.

**Comment by Donnnno** [comment]
Oops, didn't notice that!

**Comment by tmo1** [comment]
> Oops, didn't notice that!

Sorry for not getting back to you earlier - I'll try to look at it in the next day or two, and merge it if everything looks good.

**Comment by tmo1** [comment]
> Oops, didn't notice that!

Perhaps I missed something, but did you make the changes I requested?

**Comment by Donnnno** [comment]
oh, I totally forgot this! Gonna change it now!

**Comment by Donnnno** [comment]
Should be good to go now!

**Comment by tmo1** [comment]
> Should be good to go now!

I think there's still one XML file missing the copyright information: app/src/main/res/values/ic_launcher_background.xml

Please fix that, and hopefully we'll be good to go.

**Comment by maverick74** [comment]
> I think there's still one XML file missing the copyright information: app/src/main/res/values/ic_launcher_background.xml
> 
> Please fix that, and hopefully we'll be good to go.

@Donnnno expected anytime soon? :)

**Comment by Donnnno** [comment]
sorry, totally forgot that one! 

But it's ready now!

**Comment by tmo1** [comment]
Thank you!

**Comment by tmo1** [comment]
Close: #20

**Comment by Donnnno** [comment]
yeah!

**Comment by Biswa96** [comment]
My apology for bringing up this old thread. I was looking into the adaptive icon issue. Then I saw this pull request. Is that icon a true SVG file or PNG file embedded into SVG?

**Comment by Donnnno** [comment]
Hi @Biswa96 I should have the SVG file somewhere :) Maybe we should make it into a material You icon as well, if that is what you're thinking.

**Pull request merged**
