### PR TITLE
Add tool to browse SMS and MMS messages exported by sms-ie

### PR DESCRIPTION
**Pull request by sta-c0000**
Hello, I wrote a simple utility to browse the SMS/MMS messages zip file exported by sms-ie.
I wrote it as a one off, not optimized or much error checking, but it seems to work OK considering its size.
(note: supports light and dark modes based on browser settings)
Only tested on one SMS/MMS export (did not test RCS, not sure if that changes anything)

Anyway, if interested pull, it's yours; otherwise thank you for sms-ie!

### CODE REVIEW

**Comment by tmo1** [comment]
This is very neat - thanks! I'd like to pull it, but I have a few questions / suggestions first:

1) Running the script throws this warning (despite apparently running correctly):
```
messages_browser.py:14: SyntaxWarning: invalid escape sequence '\S'
  URL_REGEX = re.compile("(https?://*\S+)")`
```
Can you comment on this?

2) Since I'm not the developer, I'd like to put it in a separate "contrib" section, and document this appropriately.

3) I'd like to include authorship and license information in the file and / or documentation.

Regarding 2 and 3, you can modify the PR appropriately, or I can make the changes.

**Comment by sta-c0000** [comment]
Oops, sorry, backslash is escape char, fixed by using raw string (or could have used double backslash).
Funny, no SyntaxWarning with my Python v3.11.2, apparently new since Python v3.12; still my mistake, and for not turning on all warnings (would have DeprecationWarning).

So a new top level "contrib" folder, documented in the main README.md?
It's a simple tool, license same as your project.  I'm ok with whatever you decide.
Cheers, thanks.

**Comment by tmo1** [comment]
> So a new top level "contrib" folder, documented in the main README.md?

I'd suggest putting a `contrib` folder under the `tools` folder, and adding a "Contrib" section to `Tools.md`.

>  It's a simple tool, license same as your project. I'm ok with whatever you decide.

I like to put a header in each file - you can copy the ones from the other tools, or I can add it after pulling.

Another point: the other tools are set as executable, so they can be run directly from the shell. Should we do the same for this one?

**Comment by sta-c0000** [comment]
All makes sense.
I'll make a new PR... (probably later).
Thanks!

**Pull request closed without merging**
