### PR TITLE
Add monochrome icon

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/tmo1/sms-ie/issues/114

### CODE REVIEW

**Comment by tmo1** [comment]
Thank you!

I tested this on AVD (Pixel 7, Android 34), and I found that the system still displayed the regular color icon, and not the new monochrome one, until I added the `<monochrome android:drawable="@drawable/ic_launcher_monochrome"/>` line to `app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml`.

**Comment by Biswa96** [comment]
Yeah, you are right. I missed the round icon. Though round icon is not required for this kind of normal drawing. Round icon is used "only if you require a different icon asset for circular masks—for example, if your branding relies on a circular shape."[^1]

[^1]: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by tmo1** [comment]
> Yeah, you are right. I missed the round icon. Though round icon is not required for this kind of normal drawing. Round icon is used "only if you require a different icon asset for circular masks—for example, if your branding relies on a circular shape."

Yes, I saw that. The round icon may not be required in our case, and I'm not sure why @Donnnno added it, but I guess that once it's there, it needs to have the monochrome tag included.

**Comment by Donnnno** [comment]
I have no idea anymore either!

**Comment by tmo1** [comment]
Thank you! Merged, and credited in [CONTRIBUTING.md](/CONTRIBUTING.md)

**Pull request merged**
