### PR TITLE
CI: Add GitHub Actions to build debug apk

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by tmo1** [comment]
I'm not that familiar with CI and Github Actions - can you explain what this does? From your issue title and from reading the code, I gather that this automates building a debug version of the app whenever changes to the app are pushed. Can you elaborate, please?

**Comment by Biswa96** [comment]
Yeah, same as @Artem13327 said.

**Comment by Biswa96** [comment]
The CI build did not run here due to first time. But you can see the CI log in my fork and download the APK file from CI artifact.

**Comment by Biswa96** [comment]
Yeah, sure. Though I did not add any "code" here 😄

**Comment by tmo1** [comment]
Okay, I read / skimmed [Understanding GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). If I understand things correctly, the point of this workflow is to enable people to use the latest code without them needing to build it manually or wait for it to make it into a release?

**Comment by Biswa96** [comment]
Yes.

**Pull request merged**
